---
# tasks file for ansible-hostname

- name: hostname definieren...
  become: true
  hostname:
    name: "{{ hostname }}"


- name: edit /etc/hosts ipv4
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '^#?127.0.0.1'
    line: '127.0.0.1 {{ hostname }} localhost'


- name: edit /etc/hosts ipv6
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '^#?::1'
    line: '::1 {{ hostname }} localhost'
